create table task_categories
(
    id          bigint generated by default as identity
        primary key,
    description varchar(255),
    name        varchar(255) not null,
    ident       varchar(255) not null
        unique
);

alter table task_categories
    owner to postgres;

grant select on task_categories to "user";

INSERT INTO public.task_categories (id, description, name, ident) VALUES (1, 'Задачи, связанные с профессиональной деятельностью', 'Работа', 'WORK');
INSERT INTO public.task_categories (id, description, name, ident) VALUES (2, 'Активности для поддержания физической формы', 'Спорт', 'SPORT');
INSERT INTO public.task_categories (id, description, name, ident) VALUES (3, 'Задачи, касающиеся личной жизни и саморазвития', 'Личное', 'PERSONAL');
INSERT INTO public.task_categories (id, description, name, ident) VALUES (4, 'Обучение и саморазвитие', 'Образование', 'EDUCATION');
INSERT INTO public.task_categories (id, description, name, ident) VALUES (5, 'Бытовые задачи и повседневные заботы', 'Домашние дела', 'HOUSEHOLD');
