create table tasks
(
    id            bigint generated by default as identity
        constraint task_pkey
            primary key,
    description   varchar(255),
    name          varchar(255) not null,
    task_category bigint
        constraint task_category_id
            references task_categories
);

alter table tasks
    owner to postgres;

grant delete, insert, select, update on tasks to "user";

INSERT INTO public.tasks (id, description, name, task_category) VALUES (6, '', 'Проснуться', 3);
INSERT INTO public.tasks (id, description, name, task_category) VALUES (7, '', 'Умыться', 3);
INSERT INTO public.tasks (id, description, name, task_category) VALUES (8, '', 'Поработать', 1);
INSERT INTO public.tasks (id, description, name, task_category) VALUES (9, '', 'Уснуть', 3);
